# Numpy
Di numpy ni ada array, untuk memudahkan perhitungan matematis


In [3]:
import numpy as np

In [1]:
height = [175, 168, 162, 154, 160]

In [2]:
weight = [45, 70, 64, 55, 49]

In [6]:
np_height = np.array(height)
np_weight = np.array(weight)

In [13]:
bmi = (np_height / np_weight) ** 2

In [14]:
print(bmi)

[15.12345679  5.76        6.40722656  7.84       10.66222407]


In [9]:
numlist = [1,2,3,4]
np_numlist = np.array([1,2,3,4])


In [10]:
numlist + numlist

[1, 2, 3, 4, 1, 2, 3, 4]

In [11]:
bmi

array([0.08641975, 0.03428571, 0.03955078, 0.05090909, 0.0666389 ])

In [16]:
bmi > 7

array([ True, False, False,  True,  True])

In [17]:
bmi[bmi>7]

array([15.12345679,  7.84      , 10.66222407])

## Random

In [20]:
height = np.round(np.random.normal(1.75, 0.2, 5000), 2)
height

array([1.69, 2.05, 1.58, ..., 1.92, 1.95, 1.49])

In [21]:
len(height)

5000

In [26]:
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
weight

array([78.55, 49.67, 58.78, ..., 60.61, 68.76, 50.3 ])

In [27]:
np_city = np.column_stack((weight, height))

In [28]:
np.mean(np_city[:,0])

60.22376000000001

In [29]:
np.median(np_city[:,0])

60.27

In [32]:
# standar deviasi
np.std(np_city[:,0])

14.967074161050984

## Array 2D

In [33]:
type(height)

numpy.ndarray

In [36]:
np_2d = np.array([[1.75, 1.68, 1.72],
                [66.4, 45.9, 50.03]])
np_2d

array([[ 1.75,  1.68,  1.72],
       [66.4 , 45.9 , 50.03]])

In [37]:
np_2d.shape

(2, 3)

In [39]:
type(np_2d)

numpy.ndarray

In [40]:
np_2d[0]

array([1.75, 1.68, 1.72])

In [41]:
np_2d[:,1:3]

array([[ 1.68,  1.72],
       [45.9 , 50.03]])